### ISSUE TITLE
Do not work by GUI, but can work when I used command

### ISSUE THREAD

**Issue by Suasy** [fedebotu/clone-anonymous-github#7]
Thank u for your efforts, I can clone the repo very conveniently.

Only a little issue, as the issue title said, I don't know if it's wrong with my operation or settings.

> HTTPSConnectionPool(host='anonymous.4open.science', port=443): Max retries exceeded with url: /api/repo/GPDiff/files/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by fedebotu** [comment]
Hi there! Yes it can happen, as you can see from [this issue](https://github.com/fedebotu/clone-anonymous-github/issues/4).

There are several workarounds however, such as proxies or VPNs

**Comment by fedebotu** [comment]
PS: see #8

**Comment by fedebotu** [comment]
Latest version solves this! :rocket:
